---
- hosts: all
  remote_user: deploy
  sudo: true
  gather_facts: false
  vars_files:
    # This playbook's group_vars/all is apparently not read if this playbook is
    # included in another playbook, so we explicitly load our default variables.
    - vars/defaults.yml

  roles:
    - testing
    - common
    - ssh
    - unattended-upgrades
    - monitoring
    - zerotier
    - ufw
