---
- hosts: all
  remote_user: deploy
  sudo: true
  gather_facts: false

  roles:
    - testing
    - common
    - ssh
    - users
    - dns
    - unattended-upgrades
    - monitoring
    # - zerotier
    - ufw
