---
- name: Ensure unattended-upgrades is installed
  apt: pkg=unattended-upgrades state=present

- name: Configure unattended upgrades
  template: src={{item.path}} dest=/etc/apt/apt.conf.d/{{item.dest}}
  with_items:
    - { path: 20auto-upgrades.j2, dest: 20auto-upgrades }
    - { path: 50unattended-upgrades.j2, dest: 50unattended-upgrades }

# FIXME: Maybe also nagios?
