---
logwatch_output: "mail"     # or stdout
logwatch_format: "text"     # or html
logwatch_mailto: "root"
logwatch_mailfrom: "root"
logwatch_range: "Yesterday" # or All or Today
logwatch_detail: "Med"      # or Low, High, or a number in [0,10] (0 being Low, 5 being Med, and 10 being High)
