---
# FIXME: Set up SSH login notifications.

- name: Lock down SSH
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config mode=0644
  notify:
    - restart sshd

- name: Test SSH configuration
  command: /usr/sbin/sshd -t
