---

##
# LOGWATCH
##

- name: Ensure logwatch is installed
  apt: pkg=logwatch state=present

- name: Configure logwatch
  template: src=logwatch.conf.j2 dest=/etc/logwatch/conf/logwatch.conf mode=0644

# FIXME: Better logwatch html template.

##
# LOGSTASH
##

- name: Ensure java is installed and up to date
  apt: pkg=openjdk-7-jre state=latest

- name: Retrieve logstash repository signing key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Add logstash repository
  apt_repository: repo='deb http://packages.elasticsearch.org/logstash/1.4/debian stable main' state=present
  register: logstash_repo

- name: Update apt cache
  apt: update_cache=yes
  when: logstash_repo|changed

- name: Ensure logstash is installed and up to date
  apt: pkg=logstash state=latest

- name: Prevent logstash-web from starting on boot
  lineinfile: dest=/etc/init/logstash-web.override line="manual" create=yes

# FIXME: Should probably just add to /etc/init/logstash.override instead of modifying the config file directly.
- name: Make logstash run as root
  replace: dest=/etc/init/logstash.conf regexp="^set(uid|gid) (.+)" replace="#set\1 \2"

- name: Configure SSH login notifications via logstash
  template: src=00ssh-login-notifications.conf.j2 dest=/etc/logstash/conf.d/00ssh-login-notifications.conf mode=0644
  notify:
    - restart logstash

- name: Ensure logstash is started
  service: name=logstash state=started

##
# LINODE LONGVIEW
##

- name: Install Linode Longview apt repository signing key
  apt_key: url=https://apt-longview.linode.com/linode.gpg state=present
  when: linode_longview_api_key is defined

- name: Add Linode Longview apt repository
  apt_repository: repo='deb http://apt-longview.linode.com/ {{ansible_distribution_release}} main' state=present
  register: longview_repo
  when: linode_longview_api_key is defined

- name: Ensure /etc/linode exists
  command: mkdir -p /etc/linode
  when: linode_longview_api_key is defined

- name: Install Linode Longview API key
  lineinfile: dest=/etc/linode/longview.key line='{{linode_longview_api_key}}' create=yes
  when: linode_longview_api_key is defined

- name: Update apt cache
  apt: update_cache=yes
  when: linode_longview_api_key is defined and longview_repo|changed

- name: Ensure Linode Longview agent is installed and up to date
  apt: pkg=linode-longview state=latest
  when: linode_longview_api_key is defined
