---
- name: Ensure logwatch is installed
  apt: pkg=logwatch state=present

- name: Configure logwatch
  template: src=logwatch.conf.j2 dest=/etc/logwatch/conf/logwatch.conf mode=0644

# FIXME: Better logwatch html template.
