---
- name: Change root password
  user: name=root password={{root_user_password}}

- name: Add and configure deploy user
  user: name={{deploy_user_username}} password={{deploy_user_password}} # shell=/usr/bin/zsh

- name: Set deploy user's authorized_keys
  authorized_key: user={{deploy_user_username}} key="{{item}}"
  with_items: deploy_user_authorized_keys

- name: Give deploy user sudo privileges
  template: src=sudoers_deploy.j2 dest=/etc/sudoers.d/{{deploy_user_username}} mode=0640
