---
Generate password hashes on a linux box like so:
# echo 'import crypt,getpass; print crypt.crypt(getpass.getpass(), "$6$YOURSALT")' | python -
#
# REQUIRED
# root_user_password: "$6$foo"

admin_user_username: "admin"
# REQUIRED
# admin_user_password: "$6$foo"
# REQUIRED
# admin_user_authorized_keys: []
